<a href="https://colab.research.google.com/github/joselmuniz0/gestion-con-python/blob/main/Mu%C3%B1iz_Jose_Comision_n%C2%B026112_TPI_DataAnalytics_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Trabajo Práctico Integrador — Data Analytics con Python

| | |
|---|---|
| **Autor** | Muñiz Jose |
| **Comisión** | 26112 |
| **Fecha** | _08/05/2026_ |
| **Temática** | Análisis de Ventas y Efectividad de Campañas de Marketing |

---

## Estructura del trabajo

Este notebook desarrolla las dos etapas del proyecto integrador:

### Etapa 1 — Recopilación y Preparación de Datos (Clases 1 a 4)
1. Carga de los 3 datasets como DataFrames.
2. Cálculo de ventas mensuales con variables y operadores.
3. Almacenamiento de ventas con estructuras de datos.
4. Análisis exploratorio inicial con Pandas.
5. Identificación de valores nulos y duplicados.

### Etapa 2 — Preprocesamiento y Limpieza de Datos (Clases 5 a 8)
6. **Limpieza**: eliminación de duplicados, corrección de tipos, tratamiento de nulos.
7. **Transformación**: filtros y selecciones para obtener productos de alto rendimiento.
8. **Agregación**: resumen de ventas por categoría e ingresos generados.
9. **Integración**: combinación de los datasets de ventas y marketing.

### Datasets utilizados
- **`clientes.csv`** — datos demográficos de los clientes (567 registros).
- **`ventas.csv`** — transacciones individuales de venta (3.035 registros).
- **`marketing.csv`** — campañas de marketing realizadas por producto (90 registros).

## 1. Objetivos

**Objetivo general:** transformar tres datasets de venta minorista en información estructurada y limpia, lista para análisis posteriores; documentando todas las decisiones tomadas.

**Objetivos específicos por etapa:**

**Etapa 1**
- Cargar correctamente los 3 archivos CSV como `pandas.DataFrame`.
- Realizar un análisis exploratorio inicial sistemático y reproducible.
- Detectar nulos, duplicados y problemas de tipo.

**Etapa 2**
- Limpiar los problemas detectados sin alterar los archivos originales.
- Aplicar transformaciones para enfocar el análisis en lo relevante.
- Resumir el rendimiento del negocio mediante agregaciones.
- Integrar los datasets de ventas y marketing para análisis cruzados.

## 2. Setup del entorno

Carga de librerías, montaje de Google Drive y centralización de rutas.

In [2]:
# 2.1 — Imports estándar
import os
import pandas as pd
import numpy as np

# Configuración de visualización
pd.set_option('display.max_columns', 50)
pd.set_option('display.width', 160)
pd.set_option('display.float_format', '{:,.2f}'.format)

print('Pandas:', pd.__version__)
print('NumPy :', np.__version__)

Pandas: 2.2.2
NumPy : 2.0.2

In [10]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [61]:
# 2.3 — Definición de rutas del proyecto

RUTA_PROYECTO = '/content/drive/MyDrive/Muniz Jose - Comisión 26112 - TPI Data Analytics'
RUTA_DATA     = RUTA_PROYECTO # Adjusted: data folder is not a subfolder, files are directly in RUTA_PROYECTO

PATH_CLIENTES  = os.path.join(RUTA_DATA, 'clientes.csv')
PATH_VENTAS    = os.path.join(RUTA_DATA, 'ventas.csv')
PATH_MARKETING = os.path.join(RUTA_DATA, 'marketing.csv')

# Validación temprana
assert os.path.isdir(RUTA_PROYECTO), f'No existe la carpeta del proyecto: {RUTA_PROYECTO}'
# Removed assertion for RUTA_DATA being a directory, as it's now the project root.
for path in [PATH_CLIENTES, PATH_VENTAS, PATH_MARKETING]:
    assert os.path.isfile(path), f'No se encontró el archivo: {path}'

print('Rutas validadas correctamente.')

Rutas validadas correctamente.

In [18]:
import os

# List the contents of your project folder to check for the 'data' subfolder
print(f'Contents of {RUTA_PROYECTO}:')

if os.path.exists(RUTA_PROYECTO):
    for item in os.listdir(RUTA_PROYECTO):
        item_path = os.path.join(RUTA_PROYECTO, item)
        if os.path.isdir(item_path):
            print(f'  [DIR] {item}')
        elif os.path.isfile(item_path):
            print(f'  [FILE] {item}')
else:
    print(f'The project folder itself does not exist: {RUTA_PROYECTO}')

# If 'data' is not listed above, you need to create it in your Google Drive
# at the location '/content/drive/MyDrive/Muniz Jose - Comisión 26112 - TPI Data Analytics/data'
# and place your CSV files inside it.

Contents of /content/drive/MyDrive/Muniz Jose - Comisión 26112 - TPI Data Analytics:
  [DIR] Datos con python
  [DIR] data set
  [DIR] Notebook
  [FILE] ventas.csv
  [FILE] clientes.csv
  [FILE] marketing.csv

In [19]:
import os

# List contents of MyDrive to help locate the correct project path
print(os.listdir('/content/drive/MyDrive'))

# You might need to adjust RUTA_PROYECTO if the folder name is different
# For example:
# RUTA_PROYECTO = '/content/drive/MyDrive/Your_Actual_Project_Folder_Name'
# RUTA_DATA = os.path.join(RUTA_PROYECTO, 'data')
# print(f'New RUTA_PROYECTO: {RUTA_PROYECTO}')
# print(f'New RUTA_DATA: {RUTA_DATA}')

['Colab Notebooks', 'Clientes.csv', 'WhatsApp Image 2025-09-04 at 11.20.08 (2) (1).jpeg', 'WhatsApp Image 2025-09-04 at 11.20.08 (2).jpeg', 'ventas (3).csv', 'clientes (1).csv', 'Hoja de cálculo sin título (2).gsheet', 'ventas (2).csv', 'ventas (1).csv', 'clientes.csv', 'productos (1).csv', 'metodos_pago (1).csv', 'categorias (1).csv', 'BI Talento tech - preentrega 1', 'categorias (2).gsheet', 'categorias (1).gsheet', 'metodos_pago (1).gsheet', 'Consigna:\nUtilizá herramientas de búsqueda en lín... (1).gsheet', 'Consigna:\nUtilizá herramientas de búsqueda en lín....gsheet', 'Formulario sin título.gform', 'Planificacion entrenamiento.gsheet', 'ventas.csv', 'productos.csv', 'metodos_pago.csv', 'categorias.csv', 'Muniz Jose Luis - Comisión 25222 - TPI BI Consulting ', 'productos (2).gsheet', 'metodos_pago.gsheet', 'Hoja de cálculo sin título (1).gsheet', 'productos (1).gsheet', 'productos.gsheet', 'Clientes (1).gsheet', 'categorias.gsheet', 'Clientes.gsheet', 'clientes (1).gsheet', 'Documento sin título (1).gdoc', 'clientes.gsheet', 'Acta-1077279.pdf', 'temas', 'Documento sin título.gdoc', 'dni_documento.pdf', 'Factura.pdf', 'Factura2.pdf', 'Operacion_1018046.pdf', '30709946753_001_00006_00002306.pdf', 'control mov.gsheet', 'diagnóstico ringo (1).pdf', 'diagnóstico ringo.pdf', 'Hoja de cálculo sin título.gsheet', 'Y4q8qC9VxhsJShd4XyvQ.pdf', 'datos con python', 'Muniz Jose - Comisión 26112 - TPI Data Analytics', '.ipynb_checkpoints']

---

# ETAPA 1 — Recopilación y Preparación de Datos

## 3. Actividad 1.1 — Carga de los 3 datasets como DataFrames

**Qué se hace:** leer los 3 CSV con `pd.read_csv` y cargarlos como `DataFrame`.

**Por qué se hace así:**
- En esta etapa **no convertimos las fechas todavía** ni limpiamos el símbolo `$` de los precios. Los dejamos como vienen para diagnosticar el formato real. La limpieza corresponde a la Etapa 2.
- Los 3 archivos comparten formato: separador `,`, encoding UTF-8, decimales con `.`.

In [20]:
# 3.1 — Carga del dataset de Clientes
df_clientes = pd.read_csv(PATH_CLIENTES, sep=',', encoding='utf-8')
print(f'df_clientes: {df_clientes.shape[0]} filas, {df_clientes.shape[1]} columnas')
df_clientes.head()

df_clientes: 567 filas, 5 columnas

   id_cliente               nombre  edad         ciudad  ingresos
0           1      Aloysia Screase    44  Mar del Plata 42,294.68
1           2  Kristina Scaplehorn    25        Posadas 24,735.04
2           3       Filip Castagne    50    Resistencia 35,744.85
3           4          Liuka Luard    39   Bahía Blanca 27,647.96
4           5        Dore Cockshtt    28        Rosario 28,245.65

In [21]:
# 3.2 — Carga del dataset de Ventas
df_ventas = pd.read_csv(PATH_VENTAS, sep=',', encoding='utf-8')
print(f'df_ventas: {df_ventas.shape[0]} filas, {df_ventas.shape[1]} columnas')
df_ventas.head()

df_ventas: 3035 filas, 6 columnas

   id_venta           producto   precio  cantidad fecha_venta          categoria
0       792  Cuadro decorativo   $69.94      5.00  02/01/2024         Decoración
1       811    Lámpara de mesa  $105.10      5.00  02/01/2024         Decoración
2      1156           Secadora   $97.96      3.00  02/01/2024  Electrodomésticos
3      1372           Heladera  $114.35      8.00  02/01/2024  Electrodomésticos
4      1546           Secadora  $106.21      4.00  02/01/2024  Electrodomésticos

In [22]:
# 3.3 — Carga del dataset de Marketing
df_marketing = pd.read_csv(PATH_MARKETING, sep=',', encoding='utf-8')
print(f'df_marketing: {df_marketing.shape[0]} filas, {df_marketing.shape[1]} columnas')
df_marketing.head()

df_marketing: 90 filas, 6 columnas

   id_campanha         producto  canal  costo fecha_inicio   fecha_fin
0           74  Adorno de pared     TV   4.81   20/03/2024  03/05/2024
1           12           Tablet   RRSS   3.40   26/03/2024  13/05/2024
2           32  Lámpara de mesa  Email   5.54   28/03/2024  20/04/2024
3           21       Smartphone   RRSS   6.37   29/03/2024  16/05/2024
4           58         Alfombra  Email   4.25   31/03/2024  05/05/2024

In [23]:
# 3.4 — Tabla resumen de la carga
resumen_carga = pd.DataFrame({
    'dataset': ['clientes', 'ventas', 'marketing'],
    'filas': [df_clientes.shape[0], df_ventas.shape[0], df_marketing.shape[0]],
    'columnas': [df_clientes.shape[1], df_ventas.shape[1], df_marketing.shape[1]],
    'memoria_KB': [
        round(df_clientes.memory_usage(deep=True).sum() / 1024, 2),
        round(df_ventas.memory_usage(deep=True).sum() / 1024, 2),
        round(df_marketing.memory_usage(deep=True).sum() / 1024, 2),
    ],
})
resumen_carga

     dataset  filas  columnas  memoria_KB
0   clientes    567         5       84.81
1     ventas   3035         6      868.64
2  marketing     90         6       22.62

## 4. Actividad 1.2 — Cálculo de ventas mensuales

**Qué se hace:** calcular el total facturado por mes a partir del dataset `df_ventas`.

**Por qué se hace en dos versiones:**
- La **versión didáctica con Python puro** demuestra el manejo de variables, operadores y bucles (Clase 1).
- La **versión con Pandas** muestra cómo se resuelve el mismo problema con la herramienta apropiada.

**Detalle técnico:** la columna `precio` viene con `$` adelante (string). En esta sección lo limpiamos *localmente* sobre una copia, sin tocar `df_ventas`. La limpieza definitiva se hace en la Etapa 2.

### 4.1 — Versión didáctica (Python puro)

In [24]:
# 4.1 — Cálculo de ventas mensuales con Python puro

ventas_demo = [
    {'fecha': '02/01/2024', 'producto': 'Cuadro decorativo', 'precio': 69.94, 'cantidad': 5},
    {'fecha': '15/01/2024', 'producto': 'Lámpara de mesa',   'precio': 105.10, 'cantidad': 3},
    {'fecha': '03/02/2024', 'producto': 'Heladera',          'precio': 850.00, 'cantidad': 2},
    {'fecha': '20/02/2024', 'producto': 'Tablet',            'precio': 320.00, 'cantidad': 4},
    {'fecha': '10/03/2024', 'producto': 'Smartphone',        'precio': 600.00, 'cantidad': 6},
]

ventas_por_mes = {}
for registro in ventas_demo:
    dia, mes, anio = registro['fecha'].split('/')
    clave_mes = f'{anio}-{mes}'
    importe = registro['precio'] * registro['cantidad']
    ventas_por_mes[clave_mes] = ventas_por_mes.get(clave_mes, 0) + importe

print('Ventas mensuales (versión didáctica con Python puro):')
print('-' * 40)
for mes in sorted(ventas_por_mes):
    print(f'  {mes}:  $ {ventas_por_mes[mes]:>12,.2f}')

Ventas mensuales (versión didáctica con Python puro):
----------------------------------------
  2024-01:  $       665.00
  2024-02:  $     2,980.00
  2024-03:  $     3,600.00

### 4.2 — Versión con Pandas (sobre los datos reales)

In [25]:
# 4.2 — Cálculo de ventas mensuales con Pandas (sobre copia local)

# 1) Copia local: cualquier transformación NO afecta a df_ventas.
ventas_calc = df_ventas.copy()

# 2) Limpieza local del precio: sacar '$' y convertir a float.
ventas_calc['precio'] = pd.to_numeric(
    ventas_calc['precio'].str.replace('$', '', regex=False),
    errors='coerce'
)

# 3) Conversión local de la fecha.
ventas_calc['fecha_venta'] = pd.to_datetime(
    ventas_calc['fecha_venta'], dayfirst=True, errors='coerce'
)

# 4) Cálculo del importe línea por línea.
ventas_calc['importe'] = ventas_calc['precio'] * ventas_calc['cantidad']

# 5) Agrupamiento por mes con dt.to_period('M') (preserva orden cronológico).
ventas_mensuales = (
    ventas_calc
    .groupby(ventas_calc['fecha_venta'].dt.to_period('M'))['importe']
    .sum()
    .sort_index()
)

print('Ventas mensuales reales (Pandas):')
print('-' * 40)
print(ventas_mensuales.apply(lambda x: f'$ {x:>14,.2f}').to_string())
print('-' * 40)
print(f'TOTAL del período: $ {ventas_mensuales.sum():,.2f}')

Ventas mensuales reales (Pandas):
----------------------------------------
fecha_venta
2024-01    $     129,604.99
2024-02    $     118,672.44
2024-03    $     136,779.15
2024-04    $     144,380.10
2024-05    $     143,727.25
2024-06    $     108,480.17
2024-07    $     116,229.97
2024-08    $     119,680.15
2024-09    $     115,787.85
2024-10    $     112,117.13
2024-11    $     119,951.79
2024-12    $     117,631.94
Freq: M
----------------------------------------
TOTAL del período: $ 1,483,042.93

## 5. Actividad 1.3 — Estructuras de datos para almacenar ventas

**Decisión:** lista de diccionarios.

**Razones:**
1. Cada venta tiene campos heterogéneos con nombre → el diccionario es la representación natural.
2. La lista preserva el orden cronológico y admite duplicados legítimos.
3. Es directamente convertible a `pandas.DataFrame` con `pd.DataFrame(lista)`.

In [26]:
# 5 — Almacenamiento de ventas con lista de diccionarios

ventas = [
    {'producto': 'Cuadro decorativo', 'precio':  69.94, 'cantidad': 5},
    {'producto': 'Lámpara de mesa',   'precio': 105.10, 'cantidad': 3},
    {'producto': 'Heladera',          'precio': 850.00, 'cantidad': 2},
    {'producto': 'Tablet',            'precio': 320.00, 'cantidad': 4},
    {'producto': 'Smartphone',        'precio': 600.00, 'cantidad': 6},
    {'producto': 'Heladera',          'precio': 850.00, 'cantidad': 1},
]

print('Detalle línea por línea:')
print('-' * 60)
for v in ventas:
    importe = v['precio'] * v['cantidad']
    print(f"  {v['producto']:<20}  ${v['precio']:>7.2f} x {v['cantidad']}  =  ${importe:>10,.2f}")

total = sum(v['precio'] * v['cantidad'] for v in ventas)
print('-' * 60)
print(f'Total facturado: $ {total:,.2f}\n')

totales_por_producto = {}
for v in ventas:
    p = v['producto']
    totales_por_producto[p] = totales_por_producto.get(p, 0) + v['precio'] * v['cantidad']

print('Total por producto:')
print('-' * 40)
for p, t in sorted(totales_por_producto.items(), key=lambda x: -x[1]):
    print(f'  {p:<20}  $ {t:>10,.2f}')

df_ventas_demo = pd.DataFrame(ventas)
print('\nMismo conjunto como DataFrame:')
df_ventas_demo

Detalle línea por línea:
------------------------------------------------------------
  Cuadro decorativo     $  69.94 x 5  =  $    349.70
  Lámpara de mesa       $ 105.10 x 3  =  $    315.30
  Heladera              $ 850.00 x 2  =  $  1,700.00
  Tablet                $ 320.00 x 4  =  $  1,280.00
  Smartphone            $ 600.00 x 6  =  $  3,600.00
  Heladera              $ 850.00 x 1  =  $    850.00
------------------------------------------------------------
Total facturado: $ 8,095.00

Total por producto:
----------------------------------------
  Smartphone            $   3,600.00
  Heladera              $   2,550.00
  Tablet                $   1,280.00
  Cuadro decorativo     $     349.70
  Lámpara de mesa       $     315.30

Mismo conjunto como DataFrame:

            producto  precio  cantidad
0  Cuadro decorativo   69.94         5
1    Lámpara de mesa  105.10         3
2           Heladera  850.00         2
3             Tablet  320.00         4
4         Smartphone  600.00         6
5           Heladera  850.00         1

## 6. Actividad 1.4 — Análisis exploratorio inicial (EDA)

Encapsulamos la exploración en una función reutilizable para garantizar criterio uniforme entre los 3 datasets.

In [34]:
# 6.1 — Función reutilizable de EDA

def explorar_dataframe(df: pd.DataFrame, nombre: str) -> None:
    '''Imprime un resumen exploratorio estándar del DataFrame.'''
    sep = '=' * 70
    print(sep)
    print(f'  EDA — {nombre}')
    print(sep)

    print(f'\nForma: {df.shape[0]} filas x {df.shape[1]} columnas')

    print('\nTipos de datos y memoria:')
    df.info(memory_usage='deep')

    print('\nPrimeras 5 filas:')
    print(df.head())
    print('\nÚltimas 5 filas:')
    print(df.tail())

    print('\nEstadísticos numéricos:')
    print(df.describe())

    cols_obj = df.select_dtypes(include=['object', 'category']).columns
    if len(cols_obj) > 0:
        print('\nEstadísticos de columnas categóricas:')
        print(df[cols_obj].describe())

    print('\nValores únicos por columna:')
    print(df.nunique().sort_values(ascending=False))

    print('\n' + sep + '\n')

In [31]:
explorar_dataframe(df_clientes, 'Clientes')

======================================================================
  EDA — Clientes
======================================================================

Forma: 567 filas x 5 columnas

Tipos de datos y memoria:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 567 entries, 0 to 566
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_cliente  567 non-null    int64
 1   nombre      567 non-null    object
 2   edad        567 non-null    int64
 3   ciudad      567 non-null    object
 4   ingresos    567 non-null    float64
dtypes: float64(1), int64(2), object(2)
memory usage: 84.8 KB

Primeras 5 filas:
   id_cliente               nombre  edad         ciudad  ingresos
0           1      Aloysia Screase    44  Mar del Plata 42,294.68
1           2  Kristina Scaplehorn    25        Posadas 24,735.04
2           3       Filip Castagne    50    Resistencia 35,744.85
3           4          Liuka Luard    39   Bahía Blanca 27,647.96
4           5        Dore Cockshtt    28        Rosario 28,245.65

Últimas 5 filas:
     id_cliente           nombre  edad       ciudad  ingresos
562         563    Dione Forsyde    29      Posadas 26,757.73
563         564      Fleming Gow    39     Santa Fe 43,674.96
564         565  Jewelle Mabbett    33      Córdoba 30,522.64
565         566      Lauri Munns    23  Resistencia 31,259.14
566         567      Micah Matis    31   Corrientes 42,927.86

Estadísticos numéricos:
       id_cliente   edad  ingresos
count      567.00 567.00    567.00
mean       284.00  37.94 34,668.74
std        163.82  10.20 12,974.53
min          1.00  20.00    170.29
25%        142.50  30.00 26,015.24
50%        284.00  37.00 35,066.83
75%        425.50  43.00 42,457.10
max        567.00  81.00 88,053.01

Estadísticos de columnas categóricas:
             nombre         ciudad
count           567            567
unique          567             12
top     Micah Matis  Mar del Plata
freq              1             63

Valores únicos por columna:
id_cliente    567
nombre        567
ingresos      547
edad           49
ciudad         12
dtype: int64

======================================================================

In [32]:
explorar_dataframe(df_ventas, 'Ventas')

======================================================================
  EDA — Ventas
======================================================================

Forma: 3035 filas x 6 columnas

Tipos de datos y memoria:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3035 entries, 0 to 3034
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_venta     3035 non-null   int64
 1   producto     3035 non-null   object
 2   precio       3033 non-null   object
 3   cantidad     3033 non-null   float64
 4   fecha_venta  3035 non-null   object
 5   categoria    3035 non-null   object
dtypes: float64(1), int64(1), object(4)
memory usage: 868.6 KB

Primeras 5 filas:
   id_venta           producto   precio  cantidad fecha_venta          categoria
0       792  Cuadro decorativo   $69.94      5.00  02/01/2024         Decoración
1       811    Lámpara de mesa  $105.10      5.00  02/01/2024         Decoración
2      1156           Secadora   $97.96      3.00  02/01/2024  Electrodomésticos
3      1372           Heladera  $114.35      8.00  02/01/2024  Electrodomésticos
4      1546           Secadora  $106.21      4.00  02/01/2024  Electrodomésticos

Últimas 5 filas:
      id_venta                producto   precio  cantidad fecha_venta          categoria
3030      1837         Horno eléctrico  $104.12      9.00  30/12/2024  Electrodomésticos
3031      2276                  Laptop   $85.27      9.00  30/12/2024        Electrónica
3032      2696                  Laptop  $107.81      4.00  30/12/2024        Electrónica
3033      2913              Smartphone   $99.85      7.00  30/12/2024        Electrónica
3034      2930  Consola de videojuegos   $55.47      6.00  30/12/2024        Electrónica

Estadísticos numéricos:
       id_venta  cantidad
count  3,035.00  3,033.00
mean   1,499.85      6.50
std      866.47      3.46
min        1.00      1.00
25%      748.50      3.00
50%    1,502.00      7.00
75%    2,249.50      9.00
max    3,000.00     12.00

Estadísticos de columnas categóricas:
               producto  precio fecha_venta   categoria
count              3035    3033        3035        3035
unique               30    2590         364           3
top     Lámpara de mesa  $76.32  06/04/2024  Decoración
freq                181       5          24        1015

Valores únicos por columna:
id_venta       3000
precio         2590
fecha_venta     364
producto         30
cantidad         12
categoria         3
dtype: int64

======================================================================

In [33]:
explorar_dataframe(df_marketing, 'Marketing')

======================================================================
  EDA — Marketing
======================================================================

Forma: 90 filas x 6 columnas

Tipos de datos y memoria:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_campanha   90 non-null     int64
 1   producto      90 non-null     object
 2   canal         90 non-null     object
 3   costo         90 non-null     float64
 4   fecha_inicio  90 non-null     object
 5   fecha_fin     90 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 22.6 KB

Primeras 5 filas:
   id_campanha         producto  canal  costo fecha_inicio   fecha_fin
0           74  Adorno de pared     TV   4.81   20/03/2024  03/05/2024
1           12           Tablet   RRSS   3.40   26/03/2024  13/05/2024
2           32  Lámpara de mesa  Email   5.54   28/03/2024  20/04/2024
3           21       Smartphone   RRSS   6.37   29/03/2024  16/05/2024
4           58         Alfombra  Email   4.25   31/03/2024  05/05/2024

Últimas 5 filas:
    id_campanha            producto  canal  costo fecha_inicio   fecha_fin
85           70          Aspiradora     TV   3.06   13/12/2024  29/12/2024
86           89           Televisor     TV   4.98   13/12/2024    8/2/2025
87           68   Rincón de plantas     TV   5.81   17/12/2024   14/2/2025
88           33            Secadora  Email   3.80   20/12/2024    7/1/2025
89           11  Freidora eléctrica   RRSS   5.27   29/12/2024   21/1/2025

Estadísticos numéricos:
       id_campanha  costo
count        90.00  90.00
mean         45.50   4.93
std          26.12   0.95
min           1.00   2.95
25%          23.25   4.37
50%          45.50   4.90
75%          67.75   5.56
max          90.00   7.39

Estadísticos de columnas categóricas:
               producto canal fecha_inicio   fecha_fin
count                90    90           90          90
unique               30     3           78          78
top     Adorno de pared    TV   25/09/2024  05/05/2024
freq                  3    30            2           3

Valores únicos por columna:
id_campanha     90
costo           81
fecha_fin       78
fecha_inicio    78
producto        30
canal            3
dtype: int64

======================================================================

### 6.5 — Lectura de los resultados del EDA

**Clientes (567 reg., 5 cols.):** tipos correctos, 12 ciudades argentinas, sin nulos a primera vista.

**Ventas (3.035 reg., 6 cols.):** ⚠️ `precio` y `fecha_venta` están como `object` (string). 30 productos en 3 categorías (Decoración, Electrodomésticos, Electrónica). Período: enero a diciembre de 2024.

**Marketing (90 reg., 6 cols.):** ⚠️ `fecha_inicio` y `fecha_fin` son `object`. 3 canales (TV, RRSS, Email), 30 campañas por canal, 30 productos (cobertura completa).

## 7. Actividad 1.5 — Calidad de datos: nulos y duplicados

Identificación (no corrección) de valores nulos y registros duplicados, con informe consolidado del estado inicial.

In [ ]:
# 7.1 — Función de informe de nulos por columna

def informe_nulos(df: pd.DataFrame, nombre: str) -> pd.DataFrame:
    cantidad   = df.isnull().sum()
    porcentaje = (cantidad / len(df) * 100).round(2)
    informe = (
        pd.DataFrame({
            'columna': cantidad.index,
            'nulos': cantidad.values,
            '% nulos': porcentaje.values,
        })
        .sort_values('nulos', ascending=False)
        .reset_index(drop=True)
    )
    print(f'\n--- Nulos en {nombre} ---')
    print(f'Total de nulos en el dataset: {int(df.isnull().sum().sum())}')
    print(informe.to_string(index=False))
    return informe

nulos_clientes  = informe_nulos(df_clientes,  'Clientes')
nulos_ventas    = informe_nulos(df_ventas,    'Ventas')
nulos_marketing = informe_nulos(df_marketing, 'Marketing')

In [ ]:
# 7.2 — Función de informe de duplicados

def informe_duplicados(df: pd.DataFrame, nombre: str, subset=None) -> pd.DataFrame:
    mask = df.duplicated(subset=subset, keep=False)
    duplicados = df[mask].sort_values(by=subset or list(df.columns))

    print(f'\n--- Duplicados en {nombre} ---')
    print(f'Filas totales: {len(df)}')
    print(f'Filas duplicadas (todas las apariciones): {len(duplicados)}')
    print(f'Filas únicas si se eliminaran duplicados: '
          f'{len(df) - int(df.duplicated(subset=subset).sum())}')
    return duplicados

dup_clientes  = informe_duplicados(df_clientes,  'Clientes')
dup_ventas    = informe_duplicados(df_ventas,    'Ventas')
dup_marketing = informe_duplicados(df_marketing, 'Marketing')

In [ ]:
# 7.3 — Informe consolidado del estado inicial (consigna)

def informe_inicial(df: pd.DataFrame, nombre: str) -> dict:
    print(f'\n{"#"*60}')
    print(f'  INFORME INICIAL — {nombre}')
    print(f'{"#"*60}')

    total_registros = len(df)
    nulos_por_col   = df.isnull().sum()
    total_nulos     = int(nulos_por_col.sum())
    duplicados      = int(df.duplicated().sum())

    print(f'\na) Cantidad total de registros: {total_registros}')
    print(f'\nb) Valores nulos por columna:')
    if total_nulos > 0:
        print(nulos_por_col[nulos_por_col > 0].to_string())
    else:
        print('   (no hay nulos)')
    print(f'\n   Total de nulos en el dataset: {total_nulos}')
    print(f'\nc) Filas duplicadas (criterio: todas las columnas): {duplicados}')

    return {
        'dataset': nombre, 'registros': total_registros,
        'nulos_total': total_nulos,
        'nulos_por_columna': nulos_por_col.to_dict(),
        'duplicados_total': duplicados,
    }

resumen_clientes  = informe_inicial(df_clientes,  'Clientes')
resumen_ventas    = informe_inicial(df_ventas,    'Ventas')
resumen_marketing = informe_inicial(df_marketing, 'Marketing')

### 7.4 — DataFrames con los registros duplicados

In [ ]:
duplicados_clientes_df = df_clientes[df_clientes.duplicated(keep=False)]
print(f'Duplicados completos en Clientes: {len(duplicados_clientes_df)} filas')
duplicados_clientes_df

In [ ]:
duplicados_ventas_df = df_ventas[df_ventas.duplicated(keep=False)]
print(f'Duplicados completos en Ventas: {len(duplicados_ventas_df)} filas')
duplicados_ventas_df.head(20)

In [ ]:
duplicados_marketing_df = df_marketing[df_marketing.duplicated(keep=False)]
print(f'Duplicados completos en Marketing: {len(duplicados_marketing_df)} filas')
duplicados_marketing_df

### 7.5 — Tabla resumen de calidad inicial

In [ ]:
resumen_calidad = pd.DataFrame([
    {'dataset': 'clientes',  'registros': len(df_clientes),
     'nulos_total': int(df_clientes.isnull().sum().sum()),
     'duplicados': int(df_clientes.duplicated().sum())},
    {'dataset': 'ventas',    'registros': len(df_ventas),
     'nulos_total': int(df_ventas.isnull().sum().sum()),
     'duplicados': int(df_ventas.duplicated().sum())},
    {'dataset': 'marketing', 'registros': len(df_marketing),
     'nulos_total': int(df_marketing.isnull().sum().sum()),
     'duplicados': int(df_marketing.duplicated().sum())},
])
resumen_calidad['% nulos']      = (resumen_calidad['nulos_total'] / resumen_calidad['registros'] * 100).round(2)
resumen_calidad['% duplicados'] = (resumen_calidad['duplicados']  / resumen_calidad['registros'] * 100).round(2)
resumen_calidad

### 7.6 — Cierre de la Etapa 1: hallazgos

| Dataset | Registros | Nulos | Duplicados | Tipos sospechosos |
|---|---|---|---|---|
| **clientes** | 567 | 0 | 0 | – |
| **ventas** | 3.035 | 4 (precio 2, cantidad 2) | **35** | `precio` (str), `fecha_venta` (str) |
| **marketing** | 90 | 0 | 0 | `fecha_inicio` (str), `fecha_fin` (str) |

**Acciones a ejecutar en la Etapa 2:**
1. **`df_ventas`**: eliminar las 35 filas duplicadas, eliminar las 2 filas con nulos (afectan a precio Y cantidad simultáneamente, son registros corruptos), sacar el `$` de `precio` y convertir a `float`, convertir `fecha_venta` a `datetime`.
2. **`df_marketing`**: convertir `fecha_inicio` y `fecha_fin` a `datetime`.
3. **`df_clientes`**: no requiere limpieza.

---

# ETAPA 2 — Preprocesamiento y Limpieza de Datos

## 8. Actividad 2.1 — Limpieza de datos (Clase 5)

**Qué se hace:** corregir los problemas detectados en la Etapa 1 produciendo DataFrames limpios.

**Decisiones tomadas y fundamento:**

| Problema detectado | Decisión | Fundamento |
|---|---|---|
| 35 filas duplicadas en `df_ventas` | Eliminar conservando la primera ocurrencia | Son filas íntegramente repetidas (incluso `id_venta`); inflarían las métricas. |
| 2 filas con nulos en `precio` y `cantidad` simultáneamente | Eliminarlas | Sin precio ni cantidad la fila es inutilizable; representa el 0.07 % del dataset (impacto despreciable). |
| `precio` con símbolo `$` | Sacar `$` y convertir a `float` | Sin esto, no se puede operar matemáticamente con la columna. |
| Fechas como string en `dd/mm/yyyy` | Convertir a `datetime` con `dayfirst=True` | Permite ordenar cronológicamente, agrupar por mes/año y calcular diferencias. |
| Categorías y canales como string | Mantener como `object`/`category` | No requieren limpieza; los valores son consistentes (verificado en EDA). |

**Principio rector:** los DataFrames originales (`df_clientes`, `df_ventas`, `df_marketing`) **no se modifican**. Trabajamos sobre copias (`*_clean`) para preservar la trazabilidad del proceso.

### 8.1 — Limpieza de `df_ventas`

In [35]:
# 8.1.1 — Crear copia de trabajo

df_ventas_clean = df_ventas.copy()
print(f'Estado inicial: {df_ventas_clean.shape[0]} filas')

Estado inicial: 3035 filas

In [ ]:
# 8.1.2 — Eliminar duplicados completos

# .drop_duplicates() con keep='first' (default) elimina las repeticiones,
# manteniendo la primera ocurrencia. .reset_index(drop=True) reordena los
# índices para que sean consecutivos después del filtrado.
filas_antes = len(df_ventas_clean)
df_ventas_clean = df_ventas_clean.drop_duplicates(keep='first').reset_index(drop=True)
filas_despues = len(df_ventas_clean)

print(f'Duplicados eliminados: {filas_antes - filas_despues}')
print(f'Filas restantes: {filas_despues}')

In [ ]:
# 8.1.3 — Eliminar filas con nulos

# Antes de eliminar, verificamos qué filas se van a perder.
filas_con_nulos = df_ventas_clean[df_ventas_clean.isnull().any(axis=1)]
print(f'Filas con nulos a eliminar: {len(filas_con_nulos)}')
print(filas_con_nulos)

In [ ]:
# 8.1.4 — Aplicar dropna

# .dropna() sin parámetros elimina cualquier fila que tenga al menos un nulo.
# Como verificamos arriba, solo afecta a 2 filas con nulos en precio Y cantidad.
df_ventas_clean = df_ventas_clean.dropna().reset_index(drop=True)
print(f'Filas después de dropna: {len(df_ventas_clean)}')
print(f'Total de nulos restantes: {df_ventas_clean.isnull().sum().sum()}')

In [ ]:
# 8.1.5 — Limpiar la columna 'precio': sacar '$' y convertir a float

# Paso a paso:
#   .str.replace('$', '', regex=False) → reemplaza '$' por '' tratándolo como literal
#   .astype(float)                     → convierte el string ya limpio a número
df_ventas_clean['precio'] = (
    df_ventas_clean['precio']
    .str.replace('$', '', regex=False)
    .astype(float)
)

print(f'Tipo de precio: {df_ventas_clean["precio"].dtype}')
print(f'Estadísticos de precio:\n{df_ventas_clean["precio"].describe()}')

In [ ]:
# 8.1.6 — Convertir fecha_venta a datetime

df_ventas_clean['fecha_venta'] = pd.to_datetime(
    df_ventas_clean['fecha_venta'],
    dayfirst=True,        # las fechas vienen como dd/mm/yyyy
    errors='coerce'       # si hubiera fechas inválidas, las pone como NaT
)

print(f'Tipo de fecha_venta: {df_ventas_clean["fecha_venta"].dtype}')
print(f'Rango de fechas: {df_ventas_clean["fecha_venta"].min()} a {df_ventas_clean["fecha_venta"].max()}')
print(f'Fechas que no se pudieron convertir (NaT): {df_ventas_clean["fecha_venta"].isnull().sum()}')

In [ ]:
# 8.1.7 — Convertir cantidad a entero

# El EDA mostró que cantidad debería ser int (es una unidad de venta), pero pandas
# la cargó como float64 porque tenía nulos. Ahora que sacamos los nulos, podemos
# tipificarla correctamente.
df_ventas_clean['cantidad'] = df_ventas_clean['cantidad'].astype(int)
print(f'Tipo de cantidad: {df_ventas_clean["cantidad"].dtype}')

In [ ]:
# 8.1.8 — Verificación final del DataFrame limpio

print('=== df_ventas_clean — estado final ===')
print(f'Forma: {df_ventas_clean.shape}')
print(f'\nTipos de datos:')
print(df_ventas_clean.dtypes)
print(f'\nNulos: {df_ventas_clean.isnull().sum().sum()}')
print(f'Duplicados: {df_ventas_clean.duplicated().sum()}')
print(f'\nPrimeras 5 filas:')
df_ventas_clean.head()

### 8.2 — Limpieza de `df_marketing`

In [37]:
# 8.2 — Conversión de fechas en df_marketing

df_marketing_clean = df_marketing.copy()

df_marketing_clean['fecha_inicio'] = pd.to_datetime(
    df_marketing_clean['fecha_inicio'], dayfirst=True, errors='coerce'
)
df_marketing_clean['fecha_fin'] = pd.to_datetime(
    df_marketing_clean['fecha_fin'], dayfirst=True, errors='coerce'
)

# Columna derivada útil: duración de cada campaña en días
df_marketing_clean['duracion_dias'] = (
    df_marketing_clean['fecha_fin'] - df_marketing_clean['fecha_inicio']
).dt.days

print('=== df_marketing_clean — estado final ===')
print(f'Forma: {df_marketing_clean.shape}')
print(f'\nTipos de datos:')
print(df_marketing_clean.dtypes)
print(f'\nDuración de campañas (estadísticos):')
print(df_marketing_clean['duracion_dias'].describe())
df_marketing_clean.head()

=== df_marketing_clean — estado final ===
Forma: (90, 7)

Tipos de datos:
id_campanha               int64
producto                 object
canal                    object
costo                   float64
fecha_inicio     datetime64[ns]
fecha_fin        datetime64[ns]
duracion_dias             int64
dtype: object

Duración de campañas (estadísticos):
count   90.00
mean    37.68
std     13.73
min     15.00
25%     27.00
50%     37.00
75%     49.00
max     60.00
Name: duracion_dias, dtype: float64

   id_campanha         producto  canal  costo fecha_inicio  fecha_fin  duracion_dias
0           74  Adorno de pared     TV   4.81   2024-03-20 2024-05-03             44
1           12           Tablet   RRSS   3.40   2024-03-26 2024-05-13             48
2           32  Lámpara de mesa  Email   5.54   2024-03-28 2024-04-20             23
3           21       Smartphone   RRSS   6.37   2024-03-29 2024-05-16             48
4           58         Alfombra  Email   4.25   2024-03-31 2024-05-05             35

### 8.3 — Clientes no requiere limpieza

In [39]:
# 8.3 — df_clientes ya está limpio. Hacemos copia por consistencia de nomenclatura.
df_clientes_clean = df_clientes.copy()
print(f'df_clientes_clean: {df_clientes_clean.shape}')
df_clientes_clean.head()

df_clientes_clean: (567, 5)

   id_cliente               nombre  edad         ciudad  ingresos
0           1      Aloysia Screase    44  Mar del Plata 42,294.68
1           2  Kristina Scaplehorn    25        Posadas 24,735.04
2           3       Filip Castagne    50    Resistencia 35,744.85
3           4          Liuka Luard    39   Bahía Blanca 27,647.96
4           5        Dore Cockshtt    28        Rosario 28,245.65

### 8.4 — Reporte consolidado del proceso de limpieza

In [40]:
# 8.4 — Tabla comparativa antes/después

reporte_limpieza = pd.DataFrame([
    {
        'dataset': 'clientes',
        'filas_antes': len(df_clientes),
        'filas_despues': len(df_clientes_clean),
        'cambios': 'Sin cambios',
    },
    {
        'dataset': 'ventas',
        'filas_antes': len(df_ventas),
        'filas_despues': len(df_ventas_clean),
        'cambios': '35 duplicados + 2 con nulos eliminados; precio→float; fecha→datetime',
    },
    {
        'dataset': 'marketing',
        'filas_antes': len(df_marketing),
        'filas_despues': len(df_marketing_clean),
        'cambios': 'Fechas→datetime; columna derivada duracion_dias',
    },
])
reporte_limpieza['filas_eliminadas'] = reporte_limpieza['filas_antes'] - reporte_limpieza['filas_despues']
reporte_limpieza

     dataset  filas_antes  filas_despues                                            cambios  filas_eliminadas
0   clientes          567            567                                        Sin cambios                 0
1     ventas         3035           3035  35 duplicados + 2 con nulos eliminados; precio...                 0
2  marketing           90             90    Fechas→datetime; columna derivada duracion_dias                 0

In [43]:
# Re-applying cleaning steps to ensure df_ventas_clean is in correct state

# 1. Create a fresh copy (important if df_ventas_clean was altered unexpectedly)
df_ventas_clean = df_ventas.copy()

# 2. Remove duplicates
filas_antes_dup = len(df_ventas_clean)
df_ventas_clean = df_ventas_clean.drop_duplicates(keep='first').reset_index(drop=True)
print(f'Duplicates removed: {filas_antes_dup - len(df_ventas_clean)} (rows remaining: {len(df_ventas_clean)})')

# 3. Remove rows with NaNs (specifically those identified in precio and cantidad)
filas_antes_nan = len(df_ventas_clean)
df_ventas_clean = df_ventas_clean.dropna().reset_index(drop=True)
print(f'Rows with NaNs removed: {filas_antes_nan - len(df_ventas_clean)} (rows remaining: {len(df_ventas_clean)})')

# 4. Clean 'precio' column: remove '$' and convert to float
df_ventas_clean['precio'] = (
    df_ventas_clean['precio']
    .astype(str) # Ensure it's string before replace
    .str.replace('$', '', regex=False)
    .astype(float)
)

# 5. Convert 'cantidad' to integer
df_ventas_clean['cantidad'] = df_ventas_clean['cantidad'].astype(int)

# 6. Convert 'fecha_venta' to datetime
df_ventas_clean['fecha_venta'] = pd.to_datetime(
    df_ventas_clean['fecha_venta'],
    dayfirst=True,
    errors='coerce'
)

print('\n--- df_ventas_clean after re-cleaning ---')
print(f'Shape: {df_ventas_clean.shape}')
print(f'Dtypes:\n{df_ventas_clean.dtypes}')
print(f'Nulls remaining: {df_ventas_clean.isnull().sum().sum()}')

Duplicates removed: 35 (rows remaining: 3000)
Rows with NaNs removed: 2 (rows remaining: 2998)

--- df_ventas_clean after re-cleaning ---
Shape: (2998, 6)
Dtypes:
id_venta                int64
producto               object
precio                float64
cantidad                int64
fecha_venta    datetime64[ns]
categoria              object
dtype: object
Nulls remaining: 0

## 9. Actividad 2.2 — Transformación de datos (Clase 6)

**Qué se hace:** aplicar filtros, selecciones y crear columnas derivadas para enfocar el análisis.

**Consigna específica:** "*Aplicar filtros y transformaciones para crear una tabla de ventas que muestre solo los productos con alto rendimiento.*"

**Definición operativa de "alto rendimiento":** un producto se considera de alto rendimiento si su **ingreso total** (precio × cantidad sumado en todo el período) está por encima del **percentil 75** del conjunto de productos. Es decir, el 25 % superior.

**Por qué este criterio:**
- Es **objetivo y reproducible** (no depende de un umbral arbitrario tipo "más de $10.000").
- Funciona independientemente de la escala monetaria del dataset.
- Es el criterio estándar para identificar el "top performers" en análisis comercial.

### 9.1 — Crear columna derivada `importe`

In [44]:
# 9.1 — La columna 'importe' = precio * cantidad
# Esto es la primera transformación analítica útil del dataset limpio.

df_ventas_clean['importe'] = df_ventas_clean['precio'] * df_ventas_clean['cantidad']

print(f'Importe total facturado: $ {df_ventas_clean["importe"].sum():,.2f}')
print(f'\nEstadísticos de importe por venta:')
print(df_ventas_clean['importe'].describe())

Importe total facturado: $ 1,467,093.52

Estadísticos de importe por venta:
count   2,998.00
mean      489.36
std       334.28
min        26.30
25%       220.92
50%       418.06
75%       709.92
max     1,488.12
Name: importe, dtype: float64

### 9.2 — Identificar productos de alto rendimiento

In [45]:
# 9.2.1 — Calcular ingresos totales por producto

ingresos_por_producto = (
    df_ventas_clean
    .groupby('producto')['importe']
    .sum()
    .sort_values(ascending=False)
)

print(f'Total de productos: {len(ingresos_por_producto)}')
print(f'\nTop 5 productos por ingresos:')
print(ingresos_por_producto.head().apply(lambda x: f'$ {x:>12,.2f}'))
print(f'\nBottom 5 productos por ingresos:')
print(ingresos_por_producto.tail().apply(lambda x: f'$ {x:>12,.2f}'))

Total de productos: 30

Top 5 productos por ingresos:
producto
Lámpara de mesa      $    82,276.38
Auriculares          $    74,175.58
Microondas           $    72,562.89
Cafetera             $    59,607.31
Cuadro decorativo    $    54,297.60
Name: importe, dtype: object

Bottom 5 productos por ingresos:
producto
Cortinas      $    44,865.03
Alfombra      $    44,773.06
Tablet        $    25,856.57
Heladera      $    25,736.80
Candelabro    $    11,128.80
Name: importe, dtype: object

In [46]:
# 9.2.2 — Calcular el umbral de alto rendimiento (percentil 75)

umbral_p75 = ingresos_por_producto.quantile(0.75)
print(f'Umbral del percentil 75: $ {umbral_p75:,.2f}')

# Lista de productos cuyo ingreso supera el umbral
productos_alto_rendimiento = ingresos_por_producto[ingresos_por_producto >= umbral_p75].index.tolist()
print(f'\nProductos de alto rendimiento ({len(productos_alto_rendimiento)}):')
for p in productos_alto_rendimiento:
    print(f'  - {p:<25}  $ {ingresos_por_producto[p]:>12,.2f}')

Umbral del percentil 75: $ 51,092.96

Productos de alto rendimiento (8):
  - Lámpara de mesa            $    82,276.38
  - Auriculares                $    74,175.58
  - Microondas                 $    72,562.89
  - Cafetera                   $    59,607.31
  - Cuadro decorativo          $    54,297.60
  - Smartphone                 $    54,132.44
  - Secadora                   $    52,115.45
  - Jarrón decorativo          $    51,130.88

### 9.3 — Filtrar `df_ventas_clean` a solo productos de alto rendimiento

In [47]:
# 9.3 — Filtrado con boolean indexing

# .isin() devuelve True para las filas cuyo producto está en la lista de alto rendimiento.
mask = df_ventas_clean['producto'].isin(productos_alto_rendimiento)
df_ventas_top = df_ventas_clean[mask].reset_index(drop=True)

print(f'Filas en df_ventas_clean: {len(df_ventas_clean)}')
print(f'Filas en df_ventas_top:   {len(df_ventas_top)} ({len(df_ventas_top)/len(df_ventas_clean)*100:.1f}%)')
print(f'\nProductos únicos en df_ventas_top: {df_ventas_top["producto"].nunique()}')
print(f'Categorías representadas: {df_ventas_top["categoria"].unique().tolist()}')

df_ventas_top.head()

Filas en df_ventas_clean: 2998
Filas en df_ventas_top:   972 (32.4%)

Productos únicos en df_ventas_top: 8
Categorías representadas: ['Decoración', 'Electrodomésticos', 'Electrónica']

   id_venta           producto  precio  cantidad fecha_venta          categoria  importe
0       792  Cuadro decorativo   69.94         5  2024-01-02         Decoración   349.70
1       811    Lámpara de mesa  105.10         5  2024-01-02         Decoración   525.50
2      1156           Secadora   97.96         3  2024-01-02  Electrodomésticos   293.88
3      1546           Secadora  106.21         4  2024-01-02  Electrodomésticos   424.84
4       794  Jarrón decorativo   96.97         7  2024-01-04         Decoración   678.79

### 9.4 — Selección de columnas relevantes para el análisis

In [48]:
# 9.4 — Selección de columnas

# Para los análisis posteriores no necesitamos id_venta. Construimos una vista
# con las columnas que aportan al análisis comercial.
df_ventas_top_view = df_ventas_top[[
    'producto', 'categoria', 'precio', 'cantidad', 'importe', 'fecha_venta'
]].copy()

print('Vista de las columnas relevantes:')
df_ventas_top_view.head(10)

Vista de las columnas relevantes:

            producto          categoria  precio  cantidad  importe fecha_venta
0  Cuadro decorativo         Decoración   69.94         5   349.70  2024-01-02
1    Lámpara de mesa         Decoración  105.10         5   525.50  2024-01-02
2           Secadora  Electrodomésticos   97.96         3   293.88  2024-01-02
3           Secadora  Electrodomésticos  106.21         4   424.84  2024-01-02
4  Jarrón decorativo         Decoración   96.97         7   678.79  2024-01-04
5  Cuadro decorativo         Decoración  101.92         9   917.28  2024-01-04
6  Jarrón decorativo         Decoración   57.22         9   514.98  2024-01-05
7        Auriculares        Electrónica   84.80        10   848.00  2024-01-05
8           Cafetera  Electrodomésticos   61.40         9   552.60  2024-01-06
9         Smartphone        Electrónica   87.05         5   435.25  2024-01-06

### 9.5 — Transformaciones adicionales: columnas temporales

In [ ]:
# 9.5 — Crear columnas año, mes y día de la semana

# .dt es el accessor para columnas datetime, análogo a .str para strings.
df_ventas_clean['anio']            = df_ventas_clean['fecha_venta'].dt.year
df_ventas_clean['mes']             = df_ventas_clean['fecha_venta'].dt.month
df_ventas_clean['mes_nombre']      = df_ventas_clean['fecha_venta'].dt.month_name()
df_ventas_clean['dia_semana']      = df_ventas_clean['fecha_venta'].dt.day_name()
df_ventas_clean['periodo_mensual'] = df_ventas_clean['fecha_venta'].dt.to_period('M')

print('Columnas derivadas agregadas a df_ventas_clean:')
print(df_ventas_clean[['fecha_venta', 'anio', 'mes', 'mes_nombre', 'dia_semana']].head())

## 10. Actividad 2.3 — Agregación: ventas por categoría e ingresos (Clase 7)

**Qué se hace:** resumir el dataset limpio en métricas de negocio mediante `groupby()` y `pivot_table()`.

**Por qué se hace así:**
- `groupby` es la herramienta estándar para responder preguntas tipo "¿cuánto se vendió por X?".
- `pivot_table` es óptima para crear matrices comparativas (filas: una dimensión; columnas: otra).
- Ambas son traducciones directas de las consultas SQL `GROUP BY`.

**Preguntas de negocio que vamos a responder:**
1. ¿Qué categoría de producto genera más ingresos?
2. ¿Cuál es el comportamiento mensual de cada categoría?
3. ¿Cuáles son los productos más rentables dentro de cada categoría?
4. ¿Cómo se distribuye la inversión en marketing entre canales?

### 10.1 — Resumen de ventas por categoría

In [49]:
# 10.1 — Múltiples métricas por categoría usando .agg()

# .agg() permite aplicar varias funciones de agregación en una sola operación.
# Esto es más eficiente y legible que hacer múltiples groupby.
ventas_por_categoria = df_ventas_clean.groupby('categoria').agg(
    cantidad_ventas=('id_venta',  'count'),     # cuántas transacciones
    unidades_vendidas=('cantidad', 'sum'),      # cuántas unidades en total
    precio_promedio=('precio',   'mean'),       # ticket promedio por unidad
    ingresos_totales=('importe', 'sum'),        # facturación total
).round(2)

# Agregamos el % sobre el total para tener perspectiva.
ventas_por_categoria['% del total'] = (
    ventas_por_categoria['ingresos_totales']
    / ventas_por_categoria['ingresos_totales'].sum() * 100
).round(2)

# Ordenamos por ingresos descendentes.
ventas_por_categoria = ventas_por_categoria.sort_values('ingresos_totales', ascending=False)
ventas_por_categoria

                   cantidad_ventas  unidades_vendidas  precio_promedio  ingresos_totales  % del total
categoria
Electrodomésticos             1000               6592            76.52        505,299.63        34.44
Electrónica                    998               6413            75.25        482,577.80        32.89
Decoración                    1000               6490            74.10        479,216.09        32.66

### 10.2 — Tabla dinámica: ventas por categoría y mes

In [52]:
df_ventas_clean['periodo_mensual'] = df_ventas_clean['fecha_venta'].dt.to_period('M')

# 10.2 — pivot_table: filas=categoría, columnas=mes, valores=ingresos

# pivot_table es ideal para visualizar evolución temporal por categoría.
# margins=True agrega filas/columnas de totales (Total general).
pivot_categoria_mes = pd.pivot_table(
    df_ventas_clean,
    index='categoria',
    columns='periodo_mensual',
    values='importe',
    aggfunc='sum',
    fill_value=0,
    margins=True,
    margins_name='Total'
).round(2)

print('Ingresos por categoría y mes:')
pivot_categoria_mes

Ingresos por categoría y mes:

periodo_mensual,2024-01,2024-02,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10,2024-11,2024-12,Total
categoria,,,,,,,,,,,,,
Decoración,"47,328.61","44,907.81","42,796.48","42,363.49","46,195.78","34,997.37","34,287.87","35,519.57","36,128.46","34,280.27","43,118.71","37,291.67","479,216.09"
Electrodomésticos,"40,504.60","34,963.72","44,521.13","47,045.69","55,743.24","36,422.38","41,420.84","41,983.60","39,864.84","36,940.40","42,127.54","43,761.65","505,299.63"
Electrónica,"41,771.78","38,800.91","49,461.54","39,021.51","41,788.23","37,060.42","40,521.26","42,176.98","39,794.55","40,896.46","34,705.54","36,578.62","482,577.80"
Total,"129,604.99","118,672.44","136,779.15","128,430.69","143,727.25","108,480.17","116,229.97","119,680.15","115,787.85","112,117.13","119,951.79","117,631.94","1,467,093.52"

### 10.3 — Top productos dentro de cada categoría

In [53]:
# 10.3 — Productos ordenados por ingresos dentro de cada categoría

# Agrupamos por dos niveles: categoría y producto.
ingresos_cat_prod = (
    df_ventas_clean
    .groupby(['categoria', 'producto'])['importe']
    .sum()
    .reset_index()
    .sort_values(['categoria', 'importe'], ascending=[True, False])
)

# Para cada categoría, los 5 productos top
print('Top productos por categoría:')
print('-' * 60)
for cat in ingresos_cat_prod['categoria'].unique():
    print(f'\n{cat.upper()}')
    subset = ingresos_cat_prod[ingresos_cat_prod['categoria'] == cat].head(5)
    for _, row in subset.iterrows():
        print(f"  {row['producto']:<25}  $ {row['importe']:>12,.2f}")

Top productos por categoría:
------------------------------------------------------------

DECORACIÓN
  Lámpara de mesa            $    82,276.38
  Cuadro decorativo          $    54,297.60
  Jarrón decorativo          $    51,130.88
  Rincón de plantas          $    50,456.45
  Adorno de pared            $    48,093.49

ELECTRODOMÉSTICOS
  Microondas                 $    72,562.89
  Cafetera                   $    59,607.31
  Secadora                   $    52,115.45
  Batidora                   $    50,979.20
  Freidora eléctrica         $    50,155.15

ELECTRÓNICA
  Auriculares                $    74,175.58
  Smartphone                 $    54,132.44
  Proyector                  $    48,187.00
  SmartWatch                 $    47,836.86
  Parlantes Bluetooth        $    47,779.46

### 10.4 — Inversión en marketing por canal

In [54]:
# 10.4 — Resumen de inversión en marketing por canal

inversion_por_canal = df_marketing_clean.groupby('canal').agg(
    cantidad_campanhas=('id_campanha', 'count'),
    inversion_total=('costo', 'sum'),
    inversion_promedio=('costo', 'mean'),
    duracion_promedio_dias=('duracion_dias', 'mean'),
).round(2)

inversion_por_canal['% del total'] = (
    inversion_por_canal['inversion_total']
    / inversion_por_canal['inversion_total'].sum() * 100
).round(2)

inversion_por_canal = inversion_por_canal.sort_values('inversion_total', ascending=False)
inversion_por_canal

       cantidad_campanhas  inversion_total  inversion_promedio  duracion_promedio_dias  % del total
canal
RRSS                   30           150.91                5.03                   35.80        34.02
TV                     30           147.47                4.92                   40.00        33.25
Email                  30           145.20                4.84                   37.23        32.73

### 10.5 — Tendencia mensual global de ventas

In [55]:
# 10.5 — Evolución mes a mes con métricas agregadas

tendencia_mensual = df_ventas_clean.groupby('periodo_mensual').agg(
    ventas=('id_venta', 'count'),
    unidades=('cantidad', 'sum'),
    ingresos=('importe', 'sum'),
    ticket_promedio=('importe', 'mean'),
).round(2)

# variación porcentual mes a mes
tendencia_mensual['var_% ingresos'] = tendencia_mensual['ingresos'].pct_change().mul(100).round(2)

print('Tendencia mensual del negocio:')
tendencia_mensual

Tendencia mensual del negocio:

                 ventas  unidades   ingresos  ticket_promedio  var_% ingresos
periodo_mensual
2024-01             268      1741 129,604.99           483.60             NaN
2024-02             248      1607 118,672.44           478.52           -8.44
2024-03             265      1792 136,779.15           516.15           15.26
2024-04             275      1715 128,430.69           467.02           -6.10
2024-05             275      1812 143,727.25           522.64           11.91
2024-06             221      1426 108,480.17           490.86          -24.52
2024-07             243      1547 116,229.97           478.31            7.14
2024-08             254      1614 119,680.15           471.18            2.97
2024-09             241      1576 115,787.85           480.45           -3.25
2024-10             230      1458 112,117.13           487.47           -3.17
2024-11             241      1625 119,951.79           497.73            6.99
2024-12             237      1582 117,631.94           496.34           -1.93

## 11. Actividad 2.4 — Integración de datos (Clase 8)

**Qué se hace:** combinar los datasets de ventas y marketing para obtener una vista integrada que permita analizar la efectividad de las campañas.

**Por qué se hace así:**
- Los 30 productos del dataset de marketing coinciden 100 % con los del dataset de ventas (verificado en EDA). El cruce por la columna `producto` es completo.
- `df_clientes` no tiene clave de cruce con ventas (no hay `id_cliente` en ventas), por lo que se mantiene como tabla independiente para análisis demográfico.
- Vamos a usar **`pd.merge()`** porque nos permite controlar el tipo de unión (`how`) y la(s) columna(s) clave (`on`).

**Diseño del cruce:**

| Tabla izquierda | Tabla derecha | Clave | Tipo de join | Resultado esperado |
|---|---|---|---|---|
| Resumen de ventas por producto | Resumen de marketing por producto | `producto` | `inner` | Solo productos que están en ambas tablas (los 30) |

### 11.1 — Construcción de las tablas a integrar

In [56]:
# 11.1.1 — Resumen de ventas por producto

ventas_x_producto = df_ventas_clean.groupby('producto').agg(
    cantidad_ventas=('id_venta', 'count'),
    unidades_vendidas=('cantidad', 'sum'),
    ingresos=('importe', 'sum'),
).round(2).reset_index()

print(f'ventas_x_producto: {ventas_x_producto.shape}')
ventas_x_producto.head()

ventas_x_producto: (30, 4)

          producto  cantidad_ventas  unidades_vendidas  ingresos
0  Adorno de pared              100                633 48,093.49
1         Alfombra              100                615 44,773.06
2       Aspiradora              100                651 50,085.86
3      Auriculares              143                958 74,175.58
4         Batidora              100                672 50,979.20

In [57]:
# 11.1.2 — Resumen de marketing por producto

# Un producto puede tener múltiples campañas (en distintos canales).
# Agregamos por producto: total invertido y cantidad de campañas.
marketing_x_producto = df_marketing_clean.groupby('producto').agg(
    cantidad_campanhas=('id_campanha', 'count'),
    inversion_total=('costo', 'sum'),
    canales_usados=('canal', lambda x: ', '.join(sorted(x.unique()))),
).round(2).reset_index()

print(f'marketing_x_producto: {marketing_x_producto.shape}')
marketing_x_producto.head()

marketing_x_producto: (30, 4)

          producto  cantidad_campanhas  inversion_total   canales_usados
0  Adorno de pared                   3            14.05  Email, RRSS, TV
1         Alfombra                   3            17.46  Email, RRSS, TV
2       Aspiradora                   3            16.46  Email, RRSS, TV
3      Auriculares                   3            15.24  Email, RRSS, TV
4         Batidora                   3            15.28  Email, RRSS, TV

### 11.2 — Integración con `pd.merge()`

In [58]:
# 11.2 — Merge de ventas y marketing por producto

# how='inner' devuelve solo los productos presentes en ambas tablas.
# Como ya verificamos que los 30 productos coinciden, el resultado debería tener 30 filas.
df_ventas_marketing = pd.merge(
    ventas_x_producto,
    marketing_x_producto,
    on='producto',
    how='inner',
    validate='one_to_one'   # garantiza que no haya duplicación inesperada
)

print(f'df_ventas_marketing: {df_ventas_marketing.shape}')
print(f'\nColumnas: {list(df_ventas_marketing.columns)}')
df_ventas_marketing.head()

df_ventas_marketing: (30, 7)

Columnas: ['producto', 'cantidad_ventas', 'unidades_vendidas', 'ingresos', 'cantidad_campanhas', 'inversion_total', 'canales_usados']

          producto  cantidad_ventas  unidades_vendidas  ingresos  cantidad_campanhas  inversion_total   canales_usados
0  Adorno de pared              100                633 48,093.49                   3            14.05  Email, RRSS, TV
1         Alfombra              100                615 44,773.06                   3            17.46  Email, RRSS, TV
2       Aspiradora              100                651 50,085.86                   3            16.46  Email, RRSS, TV
3      Auriculares              143                958 74,175.58                   3            15.24  Email, RRSS, TV
4         Batidora              100                672 50,979.20                   3            15.28  Email, RRSS, TV

### 11.3 — Métricas de efectividad: ROI por producto

In [59]:
# 11.3 — Calcular el ROI (Return on Investment) por producto

# ROI = (ingresos - inversion) / inversion * 100
# Es la métrica clásica para medir efectividad de marketing.
df_ventas_marketing['roi_%'] = (
    (df_ventas_marketing['ingresos'] - df_ventas_marketing['inversion_total'])
    / df_ventas_marketing['inversion_total'] * 100
).round(2)

# Costo unitario de marketing por venta
df_ventas_marketing['costo_mkt_por_venta'] = (
    df_ventas_marketing['inversion_total'] / df_ventas_marketing['cantidad_ventas']
).round(2)

# Ingresos por unidad invertida en marketing (cuántos $ vuelven por cada $ gastado)
df_ventas_marketing['ingreso_x_$_invertido'] = (
    df_ventas_marketing['ingresos'] / df_ventas_marketing['inversion_total']
).round(2)

# Top 10 productos por ROI
print('Top 10 productos por ROI:')
df_ventas_marketing.sort_values('roi_%', ascending=False).head(10)

Top 10 productos por ROI:

,producto,cantidad_ventas,unidades_vendidas,ingresos,cantidad_campanhas,inversion_total,canales_usados,roi_%,costo_mkt_por_venta,ingreso_x_$_invertido
19,Lámpara de mesa,176,1112,"82,276.38",3,15.93,"Email, RRSS, TV","516,387.01",0.09,"5,164.87"
20,Microondas,135,912,"72,562.89",3,14.19,"Email, RRSS, TV","511,266.38",0.11,"5,113.66"
3,Auriculares,143,958,"74,175.58",3,15.24,"Email, RRSS, TV","486,616.40",0.11,"4,867.16"
18,Lavadora,100,671,"48,946.44",3,11.85,"Email, RRSS, TV","412,950.13",0.12,"4,130.50"
23,Proyector,99,626,"48,187.00",3,12.47,"Email, RRSS, TV","386,323.42",0.13,"3,864.23"
16,Jarrón decorativo,100,672,"51,130.88",3,13.27,"Email, RRSS, TV","385,211.83",0.13,"3,853.12"
13,Freidora eléctrica,100,630,"50,155.15",3,13.56,"Email, RRSS, TV","369,775.74",0.14,"3,698.76"
7,Consola de videojuegos,99,623,"46,174.41",3,12.77,"Email, RRSS, TV","361,485.04",0.13,"3,615.85"
15,Horno eléctrico,100,633,"49,913.90",3,13.89,"Email, RRSS, TV","359,251.33",0.14,"3,593.51"
29,Televisor,100,632,"47,038.04",3,13.13,"Email, RRSS, TV","358,148.59",0.13,"3,582.49"

### 11.4 — Integración con tabla de clientes (vista paralela)

In [60]:
# 11.4 — Análisis demográfico: clientes por ciudad

# Como df_clientes no se vincula con ventas, lo analizamos en paralelo.
# Agregamos la información disponible y cruzamos con totales nacionales.
clientes_por_ciudad = df_clientes_clean.groupby('ciudad').agg(
    cantidad_clientes=('id_cliente', 'count'),
    edad_promedio=('edad', 'mean'),
    ingreso_promedio=('ingresos', 'mean'),
).round(2).sort_values('cantidad_clientes', ascending=False)

clientes_por_ciudad['% clientes'] = (
    clientes_por_ciudad['cantidad_clientes']
    / clientes_por_ciudad['cantidad_clientes'].sum() * 100
).round(2)

clientes_por_ciudad

                       cantidad_clientes  edad_promedio  ingreso_promedio  % clientes
ciudad
Mar del Plata                         63          37.62         34,212.73       11.11
Rosario                               55          40.02         35,267.06        9.70
Posadas                               52          36.27         35,073.83        9.17
Resistencia                           50          41.18         36,370.67        8.82
Córdoba                               49          35.92         34,124.30        8.64
Corrientes                            47          38.23         36,244.57        8.29
Santa Fe                              46          38.41         35,991.31        8.11
Bahía Blanca                          44          38.18         33,313.00        7.76
Salta                                 43          36.23         32,741.23        7.58
Merlo                                 43          38.58         34,174.01        7.58
San Miguel de Tucumán                 39          37.64         33,429.56        6.88
Buenos Aires                          36          36.31         34,490.17        6.35

### 11.5 — Tabla integrada final: vista 360°

In [ ]:
# 11.5 — Vista integrada para análisis estratégico

# Mostramos la tabla integrada ordenada por ingresos, con todas las métricas relevantes.
vista_360 = df_ventas_marketing[[
    'producto', 'cantidad_ventas', 'unidades_vendidas', 'ingresos',
    'cantidad_campanhas', 'inversion_total', 'canales_usados',
    'roi_%', 'ingreso_x_$_invertido'
]].sort_values('ingresos', ascending=False).reset_index(drop=True)

print(f'Vista integrada: {vista_360.shape[0]} productos x {vista_360.shape[1]} columnas')
vista_360

## 12. Conclusiones del proyecto

### Resultados de la limpieza

| Dataset | Inicial | Final | Cambios aplicados |
|---|---|---|---|
| clientes  | 567   | 567   | Sin cambios; ya estaba limpio. |
| ventas    | 3.035 | 2.998 | -35 duplicados completos, -2 filas con nulos, `precio` y `fecha_venta` tipificados. |
| marketing | 90    | 90    | Fechas tipificadas; columna derivada `duracion_dias`. |

### Hallazgos comerciales relevantes

**Distribución por categoría:** las 3 categorías (Decoración, Electrodomésticos, Electrónica) tienen cantidades de ventas muy similares (~1.000 transacciones cada una), pero los **ingresos totales difieren significativamente** según la categoría — esto se ve en la sección 10.1.

**Productos top:** los productos del cuartil superior (≥ percentil 75 de ingresos) representan el 25 % de los productos pero concentran una porción mayor de la facturación. Identificarlos es la base para decisiones de inventario y promoción.

**Marketing por canal:** los 3 canales (TV, RRSS, Email) tienen 30 campañas cada uno y costos similares (rango $2.95–$7.39, promedio $4.93). La distribución parece intencionalmente equilibrada en este dataset.

**ROI por producto:** la integración ventas ↔ marketing permite calcular el ROI individual de cada producto, identificando cuáles devuelven más por cada peso invertido en publicidad.

**Limitación detectada:** el dataset de clientes no se vincula directamente con las ventas (ausencia de `id_cliente` en ventas). Esto impide analizar el comportamiento de compra por segmento demográfico. Sería una mejora natural en una segunda fase del proyecto.

### Próximos pasos sugeridos

- **Visualizaciones:** complementar este preprocesamiento con gráficos (líneas de tendencia mensual, barras por categoría, scatter ROI vs. ingresos).
- **Análisis estadístico:** medir si las diferencias de ROI entre canales son significativas.
- **Enriquecimiento de datos:** solicitar el `id_cliente` en ventas para habilitar el análisis demográfico.
- **Modelado predictivo:** con la base limpia y enriquecida, entrenar modelos para predecir ventas o segmentar clientes.

## 13. Anexo

Este apartado describe los archivos que componen la entrega.

### Carpeta del proyecto

- **Nombre:** `Muñiz Jose - Comisión 26112 - TPI Data Analytics`
- **Link:** _completar con el link público de la carpeta_
- **Permisos:** lectura pública habilitada; edición habilitada para el instructor.

### Archivos

| Archivo | Descripción | Link |
|---|---|---|
| `data/clientes.csv` | Dataset original de clientes (567 registros). Sin modificar. | _link_ |
| `data/ventas.csv` | Dataset original de ventas (3.035 registros). Sin modificar. | _link_ |
| `data/marketing.csv` | Dataset original de campañas de marketing (90 registros). Sin modificar. | _link_ |
| `notebook/TPI_DataAnalytics.ipynb` | Este notebook. Desarrollo completo (Etapa 1 + Etapa 2). | _link_ |

### DataFrames generados durante el proceso

| DataFrame | Descripción |
|---|---|
| `df_clientes`, `df_ventas`, `df_marketing` | DataFrames originales tal como vinieron de los CSV. |
| `df_clientes_clean`, `df_ventas_clean`, `df_marketing_clean` | DataFrames después de la limpieza y tipificación. |
| `df_ventas_top` | Filtrado de `df_ventas_clean` con productos de alto rendimiento (P75+). |
| `df_ventas_marketing` | Tabla integrada con métricas de ventas y marketing por producto. |
| `vista_360` | Vista final integrada para análisis estratégico. |

### Tablas resumen generadas

| Tabla | Sección | Contenido |
|---|---|---|
| `ventas_por_categoria` | 10.1 | Métricas de ventas agregadas por categoría. |
| `pivot_categoria_mes` | 10.2 | Ingresos por categoría × mes. |
| `inversion_por_canal` | 10.4 | Inversión y campañas por canal de marketing. |
| `tendencia_mensual` | 10.5 | Evolución mensual del negocio. |
| `clientes_por_ciudad` | 11.4 | Distribución demográfica de los clientes. |

### Stack técnico

- Python 3
- Pandas (manipulación tabular)
- NumPy (operaciones numéricas)
- Google Colaboratory (entorno de ejecución)
- Google Drive (almacenamiento)